#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/cassandra_configs

- name: "Create local cache folder"
  ansible.builtin.file:
    path: "{{ local_cache }}/{{ cluster }}"
    state: "directory"

- name: "Check cached copy of Cassandra config"
  ansible.builtin.stat:
    path: "{{ local_cache }}/{{ cassandra_yaml }}.orig"
  register: cassandra_yaml_cache

- name: "Download cassandra configs to local cache"
  ansible.builtin.shell:
    cmd: |
      wget -O {{ cassandra_tar }} {{ cassandra_tar_url }};
      tar -z --extract --to-stdout --file {{ cassandra_tar }} {{ conf_in_tar }}/cassandra.yaml > {{ local_cache }}/{{ cassandra_yaml }}.orig;
      tar -z --extract --to-stdout --file {{ cassandra_tar }} {{ conf_in_tar }}/jvm-server.options > {{ local_cache }}/{{ jvm_server_options }}.orig;
      tar -z --extract --to-stdout --file {{ cassandra_tar }} {{ conf_in_tar }}/jvm11-server.options > {{ local_cache }}/{{ jvm11_server_options }}.orig;
  when: not cassandra_yaml_cache.stat.exists

- name: "Process cassandra.yaml overrides"
  ansible.builtin.template:
    src: "cassandra-local.yaml.j2"
    dest: "{{ local_cache }}/cassandra-local.yaml"

- name: "Load cassandra.yaml files"
  ansible.builtin.set_fact:
    c8_yaml_orig: "{{ lookup('file', '{{ local_cache }}/{{ cassandra_yaml }}.orig') }}"
    c8_yaml_local: "{{ lookup('file', '{{ local_cache }}/cassandra-local.yaml') }}"

- name: "Merge cassandra.yaml files"
  ansible.builtin.set_fact:
    c8_yaml: "{{ c8_yaml_orig | merge_yaml_strings(c8_yaml_local) }}"

- name: "Save cassandra.yaml to local cache"
  ansible.builtin.copy:
    dest: "{{ local_cache }}/{{ cluster }}/{{ cassandra_yaml }}"
    content: "{{ c8_yaml }}"

- name: "Copy jvm-server.options file"
  ansible.builtin.copy:
    src: "{{ local_cache }}/{{ item }}.orig"
    dest: "{{ local_cache }}/{{ cluster }}/{{ item }}"
  loop: ["{{ jvm_server_options }}", "{{ jvm11_server_options }}"]

- name: "Patch jvm-server.options file"
  ansible.posix.patch:
    src: "jvm-server.options.patch"
    dest: "{{ local_cache }}/{{ cluster }}/{{ jvm_server_options }}"

- name: "Patch jvm11-server.options file"
  ansible.posix.patch:
    src: "jvm11-server.options.patch"
    dest: "{{ local_cache }}/{{ cluster }}/{{ jvm11_server_options }}"
