#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/jolokia

- block:

  - name: "Copy Jolokia agent JAR to cluster"
    ansible.builtin.copy:
      src: "{{ local_cache }}/{{ jolokia_jar }}"
      dest: "{{ deploy_docker_folder }}/{{ jolokia_jar }}"

  when: use_monitoring
