#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/jolokia

- block:

  - name: "Create local cache folder"
    ansible.builtin.file:
      path: "{{ local_cache }}"
      state: "directory"

  - name: "Check cached copy of Jolokia agent"
    ansible.builtin.stat:
      path: "{{ local_cache }}/{{ jolokia_jar }}"
    register: jolokia_jar_cache

  - name: "Download Jolokia agent JAR to local filesystem"
    ansible.builtin.shell:
      cmd: |
        wget -O - {{ jolokia_tar }} |
        tar -z --extract --to-stdout --file - {{ jolokia_agent_in_tar }} > {{ local_cache }}/{{ jolokia_jar }}
    when: not jolokia_jar_cache.stat.exists

  when: use_monitoring
