extends: default
ignore: |
  /.ansible/
  /_venv/
  .cache/
rules:
  document-start:
    present: true
    ignore: |
      **/meta/main.yml
  line-length:
    max: 132
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    ignore: |
      **/cassandra_configs/tasks/main.yml
  truthy:
    # "on" as a key in workflows confuses things
    ignore: |
      /.github/workflows/
  indentation:
    indent-sequences: consistent
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
