# copy of /sdf/group/rubin/sw/profile.d/50-squid-proxy.conf
export SQUID_PROXY=http://sdfproxy.sdf.slac.stanford.edu:3128
export http_proxy=${SQUID_PROXY}
export https_proxy=${SQUID_PROXY}
export HTTP_PROXY=${SQUID_PROXY}
export HTTPS_PROXY=${SQUID_PROXY}
export no_proxy='.slac.stanford.edu,localhost,127.0.0.1'
export NO_PROXY=${no_proxy}
