---

apdb_test:
  children:
    apdb_test_rack1:
  vars:
    node_datacenter: "dc-prompt-test"

apdb_test_rack1:
  hosts:
    sdfk8sk007:
      ansible_host: sdfk8sk007.sdf.slac.stanford.edu
      cassandra_seed: true
    sdfk8sk008:
      ansible_host: sdfk8sk008.sdf.slac.stanford.edu
    sdfk8sk009:
      ansible_host: sdfk8sk009.sdf.slac.stanford.edu
  vars:
    node_rack: "rack-1"
