# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for roles/telegraf

- name: "Check for telegraf config directory"
  ansible.builtin.stat:
    path: "{{ telegraf_config_path }}"
  register: telegraf_etc_stat

- name: "Install telegraf configs"
  when: telegraf_etc_stat.stat.exists
  become: true
  become_method: "ansible.builtin.sudo"
  block:

    - name: "Install telegraf scripts"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ telegraf_config_path }}/{{ item }}"
        mode: "0644"
      loop: ["cassandra-metrics-rename.py", "zpool-health.py"]
      notify: "Restart telegraf"

    - name: "Install telegraf config files"
      ansible.builtin.template:
        src: "{{ item }}.conf.j2"
        dest: "{{ telegraf_config_path }}/{{ item }}.conf"
        mode: "0644"
      loop: ["90-cassandra", "90-zfs", "90-tags"]
      notify: "Restart telegraf"
