#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/telegraf

- name: "Check for /etc/telegraf/telegraf.d"
  ansible.builtin.stat:
    path: /etc/telegraf/telegraf.d
  register: etc_telegraf

- block:

  - name: "Install telegraf filter script"
    ansible.builtin.copy:
      src: "files/cassandra-metrics-rename.py"
      dest: "/etc/telegraf/telegraf.d/cassandra-metrics-rename.py"
      mode: "0644"
    notify: "Restart telegraf"

  - name: "Install zpool health script"
    ansible.builtin.copy:
      src: "files/zpool-health.py"
      dest: "/etc/telegraf/telegraf.d/zpool-health.py"
      mode: "0644"
    notify: "Restart telegraf"

  - name: "Install telegraf config for cassandra"
    ansible.builtin.template:
      src: "90-cassandra.conf.j2"
      dest: "/etc/telegraf/telegraf.d/90-cassandra.conf"
      mode: "0644"
    notify: "Restart telegraf"

  - name: "Install telegraf config for zfs"
    ansible.builtin.template:
      src: "90-zfs.conf.j2"
      dest: "/etc/telegraf/telegraf.d/90-zfs.conf"
      mode: "0644"
    notify: "Restart telegraf"

  become: true
  become_method: "ansible.builtin.sudo"
  when: etc_telegraf.stat.exists
