# SPDX-License-Identifier: GPL-3.0-or-later
galaxy_info:
  author: LSST Data Managment team
  description: Generate/extract credentials used by for Cassandra and S3 storage.
  license: GPL-3.0-or-later

  min_ansible_version: "2.14"

  galaxy_tags: []

dependencies: []
