---

- name: "Start Cassandra node"
  community.docker.docker_compose_v2:
    state: present
    project_src: "{{ deploy_docker_folder }}"
    wait: true
    wait_timeout: 60

# Wait until Cassandra responds on native port.
- name: "Wait for Cassandra node"
  ansible.builtin.wait_for:
    port: 9042
    timeout: 300
    sleep: 3
