---
# `deploy_folder` needs to be specified on per-cluster basis.
deploy_folder: ""
deploy_docker_folder: "{{ deploy_folder }}/docker"

# Docker image and version (tag) to use.
cassandra_image_name: cassandra
cassandra_version: 4.1.9

# Service name for docker-compose
service_name: cassandra

# If `use_monitoring` is set to false then telegraf configuration will be
# skipped and jolokia will not be used.
use_monitoring: true
# Jolokia for monitoring JMX via REST: https://github.com/jolokia/jolokia
# version 1.7 should be used for now, 2.x was not tested.
jolokia_version: 1.7.2

# Location on controller node used to cache various files.
local_cache: "{{ playbook_dir }}/.cache"
group_local_cache: '{{ playbook_dir }}/.cache/{{ cluster_group_name | default("_any_") }}'

# Directory for data on remote host, it must be created before cluster is
# deployed, and its ownership needs to be set to UID=999. Individual clusters
# would usually override this location.
data_dir: /data

# Directory for cassandra logs on remote host, it must be created before
# cluster is deployed, and its ownership needs to be set to UID=999. Individual
# clusters would usually override this location.
logs_dir: /var/log/cassandra

# Set to true for clusters that need Cassandra password authentication.
use_password: false

# Specifies where credentials for new Cassandra accounts come from:
#   - "hashi_vault" to get credentails from HashiCorp Vault.
#     Using HashiCorp Vault requires $VAULT_ADDR and "vault login".
credentials_source:

# Path for regular user credentials in HashiCorp Vault.
hashi_vault_user_path: "rubin/usdf-apdb-dev/apdb-prod"

# Path for superuser credentials in HashiCorp Vault.
hashi_vault_super_path: "rubin/usdf-apdb-dev/apdb-prod"

# Maunt point for HashiCorp Vault.
hashi_vault_mount_point: "secret"

# Comma-separated set of seed node names from the set of nodes in the play.
cluster_seed_hosts_names: >-
  {%- for h in ansible_play_hosts_all if hostvars[h].cassandra_seed | default(false) -%}
    {{- "," if not loop.first -}}
    {{ hostvars[h].ansible_host }}
  {%- endfor -%}

# UID of the cassandra user in Docker container.
cassandra_user_uid: "999"
