---
# `deploy_folder` needs to be specified on per-cluster basis.
deploy_folder: ""
deploy_docker_folder: "{{ deploy_folder }}/docker"

# Docker image and version (tag) to use.
cassandra_image_name: cassandra
cassandra_version: 4.1.9

# Service name for docker-compose
service_name: cassandra

# If `use_monitoring` is set to false then telegraf configuration will be
# skipped and jolokia will not be used.
use_monitoring: true
# Jolokia for monitoring JMX via REST: https://github.com/jolokia/jolokia
# version 1.7 should be used for now, 2.x was not tested.
jolokia_version: 1.7.2

# Location on controller node used to cache various files.
local_cache: "{{ playbook_dir }}/.cache"
group_local_cache: '{{ playbook_dir }}/.cache/{{ cluster_unique_id | default("_any_") }}'

# Directory for data on remote host, it must be created before cluster is
# deployed, and its ownership needs to be set to UID=999. Individual clusters
# would usually override this location.
data_dir: /data

# Directory for cassandra logs on remote host, it must be created before
# cluster is deployed, and its ownership needs to be set to UID=999. Individual
# clusters would usually override this location.
logs_dir: /var/log/cassandra

# Set to true for clusters that need Cassandra password authentication.
use_password: false

# Specifies where credentials for new Cassandra accounts come from:
#   - "hashi_vault" to get credentails from HashiCorp Vault.
#     Using HashiCorp Vault requires $VAULT_ADDR and "vault login".
credentials_source:

# Path for regular user credentials in HashiCorp Vault.
hashi_vault_user_path: "rubin/usdf-apdb-dev/apdb-prod"

# Path for superuser credentials in HashiCorp Vault.
hashi_vault_super_path: "rubin/usdf-apdb-dev/apdb-prod"

# Maunt point for HashiCorp Vault.
hashi_vault_mount_point: "secret"

# Comma-separated set of seed node names from the set of nodes in the play.
cluster_seed_hosts_names: >-
  {%- for h in ansible_play_hosts_all if hostvars[h].cassandra_seed | default(false) -%}
    {{- "," if not loop.first -}}
    {{ hostvars[h].ansible_host }}
  {%- endfor -%}

# UID of the cassandra user in Docker containers (both cassandra and medusa).
cassandra_user_uid: "999"

#
# Backup-related options.
#

# Must be set to true to enable support medusa backups.
use_backups: false

medusa_image_name: k8ssandra/medusa
medusa_version: 0.25.0

backup_service_name: medusa
backup_storage_provider: s3_compatible
backup_bucket_name: usdf-apdb-prod
backup_aws_key_file: /run/secrets/medusa-minio-credentials
backup_hashi_vault_aws_path: rubin/usdf-apdb-prod/s3
backup_prefix: medusa_backup_{{ cluster_unique_id }}
backup_transfer_max_bandwidth: 500MB/s
backup_concurrent_transfers: 1
backup_s3_host: s3dfrgw.slac.stanford.edu
backup_s3_port: 443

# Jolokia is needed for both monitoring and backups.
need_jolokia: "{{ use_monitoring or use_backups }}"
