---
cluster_name: "APDB USDF test"
cluster_unique_id: "apdb_test"
deploy_folder: "/sdf/home/r/rubincas/apdb_deploy"
data_dir: "/zfspool/cassandra/apdb-cluster-test"
logs_dir: "/zfspool/cassandra/logs"

use_password: true
make_credentials_source: "hashi_vault"
hashi_vault_user_path: "rubin/usdf-apdb-test/cassandra"
hashi_vault_super_path: "rubin/usdf-apdb-test/cassandra-super"

use_backups: true
