---
cluster_name: "APDB USDF dev cluster"
cluster_unique_id: "apdb_dev"
deploy_folder: "/sdf/home/r/rubincas/apdb_deploy"
data_dir: "/zfspool/cassandra/apdb-cluster-dev"
logs_dir: "/zfspool/cassandra/logs"

use_password: true
make_credentials_source: "hashi_vault"
hashi_vault_user_path: "rubin/usdf-apdb-dev/cassandra"
hashi_vault_super_path: "rubin/usdf-apdb-dev/cassandra-super"
hashi_vault_mount_point: "secret"

use_backups: true
