# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for prep_restore

- name: "Install cassandra-medusa in virtual environment"
  ansible.builtin.pip:
    name: "cassandra-medusa"
    virtualenv: "{{ prep_restore_medusa_venv }}"
    virtualenv_command: "python3 -m venv"
  environment:
    http_proxy: "{{ prep_restore_http_proxy }}"
    https_proxy: "{{ prep_restore_https_proxy }}"

- name: "Create .bashrc.d directory if it doesn't exist"
  ansible.builtin.file:
    path: "~/.bashrc.d"
    state: "directory"
    mode: "0750"

- name: "Add bashrc entry to activate medusa virtual environment"
  ansible.builtin.template:
    src: 60-activate-medusa-env.conf
    dest: "~/.bashrc.d/60-activate-medusa-env.conf"
    mode: "0644"

- name: "Create folder for cassandra"
  ansible.builtin.file:
    path: "{{ deploy_folder }}/cassandra"
    state: "directory"
    mode: "0750"

- name: "Install Cassandra"
  ansible.builtin.unarchive:
    src: "{{ prep_restore_c8_download_uri }}"
    dest: "{{ deploy_folder }}/cassandra"
    remote_src: true
  environment:
    http_proxy: "{{ prep_restore_http_proxy }}"
    https_proxy: "{{ prep_restore_https_proxy }}"

- name: "Get credentials for Cassandra"
  ansible.builtin.import_role:
    name: make_credentials
  vars:
    make_credentials_account: "cassandra_super"
    make_credentials_var: cassandra_super_credentials

- name: "Create folder for restore configs"
  ansible.builtin.file:
    path: "{{ deploy_folder }}/cluster-restore"
    state: "directory"
    mode: "0750"

- name: "Copy medusa config to restore folder"
  ansible.builtin.template:
    src: "medusa.ini.j2"
    dest: "{{ deploy_folder }}/cluster-restore/medusa.ini"
    mode: "0600"
