# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for roles/medusa_configs

- name: "Generate config files for cassandra-medusa"
  when: use_backups
  block:

    - name: "Ask Vault for AWS secrets"
      delegate_to: localhost
      import_role:
        name: make_credentials
      vars:
        credentials_account: "backup_s3"
        credentials_var: aws_credentials

    - ansible.builtin.set_fact:
        medusa_aws_access_key: "{{ aws_credentials.access_key }}"
        medusa_aws_secret_key: "{{ aws_credentials.secret_key }}"

    - name: "Copy AWS secret to cluster"
      ansible.builtin.template:
        src: "medusa-minio-credentials.j2"
        dest: "{{ deploy_docker_folder }}/medusa-minio-credentials"
        mode: 0o600

    - name: "Set AWS secret ACL"
      ansible.posix.acl:
        path: "{{ deploy_docker_folder }}/medusa-minio-credentials"
        etype: user
        entity: "{{ cassandra_user_uid }}"
        permissions: r
        state: present

    - name: "Copy medusa config to cluster"
      ansible.builtin.template:
        src: "medusa.ini.j2"
        dest: "{{ deploy_docker_folder }}/medusa.ini"
        mode: "644"

    - name: "Copy cassandra credentials to the host."
      when: use_password
      block:

        - name: "Retrieve Cassandra credentials"
          import_role:
            name: make_credentials
          vars:
            credentials_account: "cassandra_super"
            credentials_var: super_credentials

        - ansible.builtin.set_fact:
            cassandra_super_username: "{{ super_credentials.username }}"
            cassandra_super_password: "{{ super_credentials.password }}"

        - name: "Copy Cassandra secret to cluster"
          ansible.builtin.template:
            src: "medusa-cassandra-credentials.env.j2"
            dest: "{{ deploy_docker_folder }}/medusa-cassandra-credentials.env"
            mode: 0o600
