# Playbook for rolling restart of Cassandra cluster
---

- name: "Rolling restart of all services"
  hosts: "{{ ansible_play_hosts }}"
  serial: 1
  gather_facts: false

  tasks:

    - name: "Stop Cassandra service"
      ansible.builtin.import_tasks: up_tasks/down-node.yml

    - name: "Stop containers"
      community.docker.docker_compose_v2:
        state: absent
        project_src: "{{ deploy_docker_folder }}"
        wait: true
        wait_timeout: 60

    - name: "Restart containers"
      ansible.builtin.import_tasks: up_tasks/up-node.yml
