# Playbook for rolling restart of Cassandra cluster
---

- name: "Rolling restart of cassandra service"
  hosts: "{{ ansible_play_hosts }}"
  serial: 1
  gather_facts: false

  tasks:

    - name: "Stop Cassandra service"
      ansible.builtin.import_tasks: up_tasks/down-node.yml

    - name: "Restart container"
      community.docker.docker_compose_v2:
        state: restarted
        services: ["{{ service_name }}"]
        project_src: "{{ deploy_docker_folder }}"
        wait: true
