# Playbook for installing and initializing Cassandra cluster
---

- name: "Generate files on local host"
  hosts: "localhost"
  gather_facts: false
  vars_files:
    # Need to read variables for a particular cluster.
    - "group_vars/{{ cluster }}.yml"
  roles:
    - jolokia_download
    - cassandra_configs

- name: "Copy files to remote nodes"
  hosts: "{{ cluster }}"
  gather_facts: false

  roles:
    - remote_folders
    - cassandra_files
    # - telegraf
