# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for roles/cassandra_accounts

# Replication factor for system_auth namespace, this assumes cluster with 3+
# nodes. For smaller clusters this needs to be overriden.
cassandra_accounts_system_auth_rf: "{{ system_auth_rf | default(3) }}"
