#SPDX-License-Identifier: MIT-0
---
# defaults file for make_credentials

# Source of credentials.
credentials_source:

# Mount point for the Vault secrets.
hashi_vault_mount_point: "secret"

# Name of the variable that contains returned credentials.
credentials_var: "credentials"
