# SPDX-License-Identifier: GPL-3.0-or-later
galaxy_info:
  author: LSST Data Management team
  description: Install configuration files and scripts for telegraf service.
  license: GPL-3.0-or-later

  min_ansible_version: "2.14"

  galaxy_tags: []

dependencies: []
